@local = http://localhost:3010 
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDEyYzMzYzQ3YWYzNjFlMDBkYzdhZTEiLCJwcm9mIjp0cnVlLCJpYXQiOjE2MTIyNzQ3MTJ9.A2i-GTm2w9pM_NWY9NuqQ-U9epI2WsrtjSaXyC-L4Ds

### Create users
POST {{local}}/api/users
Content-Type: application/json

{
    "firstName": "Marina",
    "lastName": "Hattemer",
    "email": "mari@gmail.com",
    "password": "12345678",
    "prof": true
}

### Signin
POST {{local}}/api/auth
Content-Type: application/json

{
    "email": "sebi@gmail.com",
    "password": "12345678"
}

### Me endpoint
GET {{local}}/api/users/me
Content-Type: application/json
x-auth-token: {{token}}

### Get favorites endpoint
GET {{local}}/api/users/profs?numbers=151719,64812
Content-Type: application/json
x-auth-token: {{token}}

### Add favorite by id prof
PUT {{local}}/api/users/803442
Content-Type: application/json
x-auth-token: {{token}}


### Create Prof 
POST {{local}}/api/profs
Content-Type: application/json
x-auth-token: {{token}}

{
  "profName": "Sebi Hattemer",
  "profTitle": "German",
  "profCity": "Ashdod",
  "profDescription": "Biology, This is a wider card with supporting text below as a natural lead-in to additional content, supporting text below as a natural ",
  "profEmail": "mari@de.de",
  "profPhone": "044444444",
  "profPrice": "300",
  "profImage": "https://scontent.fsdv1-2.fna.fbcdn.net/v/t31.0-8/18920731_1054291061371251_3460332876391398025_o.jpg?_nc_cat=102&ccb=2&_nc_sid=cdbe9c&_nc_ohc=hJXqIxlnIqwAX-FPP9O&_nc_ht=scontent.fsdv1-2.fna&oh=5137d90b4b61b9ea02f0e4d93a5622ae&oe=603A1F53"
}

### Update Prof by id
PUT {{local}}/api/profs/834577
Content-Type: application/json
x-auth-token: {{token}}

{
  "profName": "Sebi Hatt",
  "profTitle": "Spanish teacher",
  "profEducation": "Cervantes",
  "profDescription": "spanish lessons",
  "profEmail": "ivan@gmail.de",
  "profPhone": "054411223",
  "profKeywords": ["spanish", "languages"],
  "profPrice": "150"
}

### Get prof by id
GET {{local}}/api/profs/834577
Content-Type: application/json
x-auth-token: {{token}}

### Delete prof by id
DELETE {{local}}/api/profs/136180
Content-Type: application/json
x-auth-token: {{token}}

### Get all profs by user id
GET {{local}}/api/profs/my-profs
Content-Type: application/json
x-auth-token: {{token}}


### Get all profs general

GET {{local}}/api/profs/all-profs
Content-Type: application/json