@local = http://localhost:3000 

### Create users
POST {{local}}/api/users
Content-Type: application/json

{
    "name": "Ivan Hattemer",
    "email": "ivan@gmail.com",
    "password": "045844587",
    "phone": "0544774126",
    "prof": true
}